### PR TITLE
fix: timeout from config during late inject

### PR DESCRIPTION
**Pull request by nair-sumesh**

### CODE REVIEW

**Comment by nair-sumesh** [comment]
Resolves [Issue](https://github.com/ui5-community/wdi5/issues/551)

**Comment by vobu** [comment]
> @vobu : could you please generate the package-lock file for the rest of the test to be executed. At my end it will add internal library dependency like last time..

sure, will do.
but before: could you also please add a test for verifying the caching of the `wdi5` config?
I'd suggest to add a dedicated `cache-config.test.ts` (or similar name) to [/test](https://github.com/ui5-community/wdi5/tree/main/test) and test for late `wdi5` injection containing the cached config

**Comment by nair-sumesh** [comment]
> > @vobu : could you please generate the package-lock file for the rest of the test to be executed. At my end it will add internal library dependency like last time..
> 
> sure, will do. but before: could you also please add a test for verifying the caching of the `wdi5` config? I'd suggest to add a dedicated `cache-config.test.ts` (or similar name) to [/test](https://github.com/ui5-community/wdi5/tree/main/test) and test for late `wdi5` injection containing the cached config

Done. let me know if this works.

**Comment by vobu** [comment]
> > > @vobu : could you please generate the package-lock file for the rest of the test to be executed. At my end it will add internal library dependency like last time..
> > 
> > 
> > sure, will do. but before: could you also please add a test for verifying the caching of the `wdi5` config? I'd suggest to add a dedicated `cache-config.test.ts` (or similar name) to [/test](https://github.com/ui5-community/wdi5/tree/main/test) and test for late `wdi5` injection containing the cached config
> 
> Done. let me know if this works.

cool, thanks for adding the test → this safeguards the caching feature!
could you now please look into the failing tests? ignore the `auth` tests for now, but please peek into the failing `JS`- and `TS`-tests.
thx again!

**Comment by nair-sumesh** [comment]
> feature!

Actually I am not able to execute the test. I will try again at weekend.
I installed the dependency using the script in package.json.
However, during test execution, I get the error that ui5 service module is not found. 
It worked last time, but not sure what's went wrong now.

**Comment by vobu** [comment]
> > feature!
> 
> Actually I am not able to execute the test. I will try again at weekend. I installed the dependency using the script in package.json. However, during test execution, I get the error that ui5 service module is not found. It worked last time, but not sure what's went wrong now.

don't forget to `npm run build` before working on any tests 😉 
(or `npm run build:watch`)

the JS tests seem to be fixed now - good job!
however, there's still the TS test for late injecting UI5 failing - could you please have a look again! thx!

**Comment by nair-sumesh** [comment]
> > > feature!
> > 
> > 
> > Actually I am not able to execute the test. I will try again at weekend. I installed the dependency using the script in package.json. However, during test execution, I get the error that ui5 service module is not found. It worked last time, but not sure what's went wrong now.
> 
> don't forget to `npm run build` before working on any tests 😉 (or `npm run build:watch`)
> 
> the JS tests seem to be fixed now - good job! however, there's still the TS test for late injecting UI5 failing - could you please have a look again! thx!

working on it. I am new to TS.
The test are complaining about missing `waitForUI5Options` in my new test at the execution of 
```json
await browser.url("http://localhost:8888")
```

Will need some more time to fix it.

**Comment by nair-sumesh** [comment]
should work now

**Review by dominikfeininger — COMMENTED** [review]
not sure about all the `global.__wdi5Config` though

**Comment by Siolto** [comment]
This PR is fine for now from my side. Thanks @nair-sumesh for the input! 
But we should generally check again were we declare all our different wdi5 specific properties. These are currently set in different places. A uniform location would be better here

**Comment by vobu** [comment]
so we're good to go it seems!
(i'll take a look at the failing auth test due to (again) `package-lock` issues)

**Pull request merged**
