### PR TITLE
Feature/chromedriver update

### PR DESCRIPTION
**Pull request by dominikfeininger**
since already noticed that a chromedriver update might be required to execute the tests if the local chrome was updated silently.

happy to see suggestions for improved parsing.

### CODE REVIEW

**Comment by vobu** [comment]
let's make this cross-platform before it's good to go

**Comment by vobu** [comment]
converting to draft as this needs cross-platform enhancement

**Comment by dominikfeininger** [comment]
https://superuser.com/questions/1144651/get-chrome-version-from-commandline-in-mac

**Comment by dominikfeininger** [comment]
In UIVeri5 we implemented primitive solution for controlling the (chrome)driver version. We have one [JSON file](https://github.com/SAP/ui5-uiveri5/blob/master/driverVersions.json) in the root of the repo, which is controlled by us and then is used to get the specified chromedriver version. It is not the best solution, but we agreed that is most stable.
 
The approach in the Dominik’s PR is looking problematic for me. From my experience of supporting UIVeri5, I have seen a lot of different setups – local and ci/cd. So I think you can’t cover all cases to get the Chrome browser version – different OS, consider docker env where the browser can be installed in many different ways/paths. Also, the versions of browser and driver are not the same – build versions are different.
 
We have a Docker setup which relies on the latest chrome + driver and that’s how we implemented it:
Get the chrome browser major version (for example 100, or 99) – we know where the browser is installed.
GET request to: [https://chromedriver.storage.googleapis.com/LATEST_RELEASE_<major_version](https://chromedriver.storage.googleapis.com/LATEST_RELEASE_%3cmajor_version)>
It returns the latest driver version for the requested browser major version:

Second similar approach is to get the latest version of chrome driver for the stable browser version:  https://chromedriver.storage.googleapis.com/LATEST_RELEASE

From my experience, again, it is always a good approach to provide an easy way to the users to control the driver version by themselves. In your case, probably good description in the docs.

**Comment by dominikfeininger** [comment]
hi @hmanchev, since you already provided the solution I would appreciate your help here ;)

**Comment by dominikfeininger** [comment]
solved by using `"chromedriver": "latest" `

**Pull request closed without merging**
