### PR TITLE
Run tests on browserstack against btp test app

### PR DESCRIPTION
**Pull request by dominikfeininger**

### CODE REVIEW

**Comment by dominikfeininger** [comment]
seems like our current browserstack plan does not allow to run the full set of tests in all browsers. Test on Browserstack runs only `basic.test.js` on Edge.

**Comment by vobu** [comment]
todo:
- [ ] more clean up
- [ ] things to watch out for: `mta.yaml` + build artifacts (`xs-app.json` and the likes), browserstack config, tests running against btp
- [ ] auto-build and -deploy app in gh action

**Comment by dominikfeininger** [comment]
@vobu is this still a "thing"

**Comment by vobu** [comment]
the goal, as in "run CI on browserstack and saucelabs w/ browsers != chrome", is still the same :)
let's track that separately though and close this PR

**Pull request closed without merging**
